import { ArrowRight, BarChart3, CheckCircle2, ChevronDown, Compass, FileText, Search, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { PageIndex, RobertGuide, SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { DreamsCarousel } from "@/components/DreamsCarousel";
import { SectionNavigator } from "@/components/SectionNavigator";
import { destinations } from "@/lib/destinations";
import { landingSectionIndex } from "@shared/navigation";

const categoryData = [
  { code: "D", title: "Debt & Funding", copy: "Access and structure capital around equipment, growth, cash-flow, and business-credit priorities.", items: "Funding · Debt review · Corporate credit" },
  { code: "R", title: "Retirement", copy: "Review retirement-plan efficiency, participation, and long-term benefit design with specialists.", items: "401(k) optimization · Auto-enrollment" },
  { code: "E", title: "Expenses", copy: "Find high-level operating-cost questions across health, benefits, energy, and utilities.", items: "Benefits review · Energy opportunities" },
  { code: "A", title: "Assets", copy: "Turn marketing, reputation, lead flow, and web presence into a more intentional growth system.", items: "Intent data · DREAMS Leads · Reviews" },
  { code: "M", title: "Money & Tax Credits", copy: "Surface credit questions that may warrant a qualified R&D, FICA, or state-credit review.", items: "R&D credit · FICA tips · State credits" },
  { code: "S", title: "Security", copy: "Review business-continuity and technical risk questions that can affect resilience and cost.", items: "Key person · Buy-sell · IT security" },
];

const faqItems = [
  ["Is there a cost?", "No. The DREAMS Score gives business owners a no-cost, estimate-based starting point for a specialist conversation."],
  ["Do I need detailed financial information?", "No. The assessment uses high-level operating inputs. A complete specialist review can gather and validate details later."],
  ["What happens after the assessment?", "You receive a report with category findings and potential next conversations. You decide which, if any, are worth exploring."],
  ["Are the figures guaranteed?", "No. Every figure is an estimate based on limited information. Qualified specialists determine final eligibility, terms, and outcomes."],
];

export default function Home() {
  const [openFaq, setOpenFaq] = useState(0);
  return <div className="app-page home-page"><SiteHeader />
    <main>
      <section className="hero-section guided-hero" id="overview"><div className="hero-grid shell"><div className="hero-copy"><span className="eyebrow"><Compass size={14} /> Guided financial clarity</span><h1>Understand your financial health across <em>six connected pillars.</em></h1><p>Use a calm, educational starting point to reflect on the operational areas that can shape your business today—and decide what deserves a closer conversation.</p><div className="hero-actions"><Link href="/assessment" className="button button-primary">Get Started with Robert <ArrowRight size={17} /></Link><Link href="/assessment" className="button button-outline">Go It Alone <ArrowRight size={17} /></Link></div><div className="hero-proof"><span><CheckCircle2 size={16} /> Educational guidance</span><span><CheckCircle2 size={16} /> Estimate-based</span><span><CheckCircle2 size={16} /> No obligation</span></div><div className="hero-guide-note"><span className="hero-guide-icon"><Sparkles size={15} /></span><p><strong>Robert, your optional guide.</strong> Start with a guided walk-through or explore the assessment independently—either way, your inputs remain high-level and educational.</p></div></div><figure className="hero-video-card paper-card"><div className="hero-video-label"><span>DREAMS Score film</span><span>01:00 overview</span></div><video className="hero-video" controls playsInline preload="metadata" aria-label="DREAMS Score one-minute opportunity overview"><source src="/manus-storage/dreams-score-hero-intro_4214a344.mp4" type="video/mp4" />Your browser does not support embedded video. Please use a modern browser to view the DREAMS Score film.</video><figcaption>One minute to see the opportunity map before you begin.</figcaption></figure></div></section>
      <DreamsCarousel />
      <section className="notice-band"><div className="shell"><ShieldCheck size={17} /><p>All figures shown are estimates based on limited information gathered. <a href={destinations.booking}>Schedule an appointment with an expert</a> for a complete, personalized proposal.</p></div></section>
      <div className="shell"><PageIndex items={landingSectionIndex} className="landing-page-index" /></div>
      <section className="how-it-works-section section-space" id="how-it-works"><div className="shell"><div className="section-heading center-heading"><span className="eyebrow">A clear four-step path</span><h2>From input to conversation.</h2><p>Use the score as a structured way to reveal areas of business value that may deserve a closer specialist review.</p></div><div className="process-grid"><article><i>01</i><Search size={23} /><h3>Start with AI visibility</h3><p>Consider how AI-assisted search and digital discovery may see your business today.</p><Link href="/ai-visibility">Start here <ArrowRight size={14} /></Link></article><article><i>02</i><FileText size={23} /><h3>Take the assessment</h3><p>Share high-level operating inputs across six DREAMS categories.</p><Link href="/assessment">Take the assessment <ArrowRight size={14} /></Link></article><article><i>03</i><BarChart3 size={23} /><h3>Get your score</h3><p>See separate annual-savings, increased-profit, and total-value estimates.</p><Link href="/sample-report/peak-manufacturing">See a sample <ArrowRight size={14} /></Link></article><article><i>04</i><Sparkles size={23} /><h3>Choose what to explore</h3><p>Bring the report to a DREAMS specialist for a focused, no-obligation conversation.</p><a href={destinations.booking}>Plan the next step <ArrowRight size={14} /></a></article></div></div></section>
      <section className="ai-promo-section" id="resources"><div className="shell ai-promo-card"><div><span className="eyebrow"><Sparkles size={14} /> Educational resource</span><h2>Explore how business discovery is changing.</h2><p>Use the AI Visibility experience as a simple resource to frame the questions a business may want to ask about digital discovery.</p><Link href="/ai-visibility" className="button button-dark">Explore AI visibility <ArrowRight size={16} /></Link></div><div className="ai-promo-visual"><span>Clarity</span><span>Context</span><span>Questions</span><span>Review</span><span>Next step</span><b>AI</b></div></div></section>
      <section className="category-section section-space" id="six-pillars"><div className="shell"><div className="section-heading"><div><span className="eyebrow">The DREAMS framework</span><h2>Six business areas. One disciplined view.</h2></div><p>Each letter represents an operational area where a business might uncover savings, profit, or protection opportunities.</p></div><div className="category-grid">{categoryData.map((category) => <article className="dream-category-card" key={category.code}><span>{category.code}</span><h3>{category.title}</h3><p>{category.copy}</p><small>{category.items}</small></article>)}</div></div></section>
      <section className="sample-section" id="sample-dashboard"><div className="shell sample-grid"><div className="sample-report-image"><div className="sample-image-glow" /><img src="/manus-storage/dreams-score-sample-report-reference_24725af7.webp" alt="DREAMS Score sample report preview" /></div><div><span className="eyebrow">Sample dashboard</span><h2>See what a clear report can make possible.</h2><p>A completed report translates broad inputs into category summaries, estimate cards, comparison bars, detailed opportunities, and plain-language next steps.</p><ul><li><CheckCircle2 size={17} /> Separate savings, profit, and total-value estimates</li><li><CheckCircle2 size={17} /> Expanded recommendations for each DREAMS category</li><li><CheckCircle2 size={17} /> Print-ready review for a specialist discussion</li></ul><Link className="button button-primary" href="/sample-report/peak-manufacturing">Explore Peak Manufacturing’s sample <ArrowRight size={16} /></Link></div></div></section>
      <section className="why-section section-space" id="goals-and-scenarios"><div className="shell"><div className="section-heading center-heading"><span className="eyebrow">Goals and scenarios</span><h2>Insight without a sales-script shortcut.</h2><p>Use your report to prepare a clearer review conversation, not as a guarantee or a prescriptive financial recommendation.</p></div><div className="why-grid"><article><CheckCircle2 size={22} /><h3>No cost for reports</h3><p>Start with a no-cost discovery tool built to show the opportunity areas that may matter most.</p></article><article><CheckCircle2 size={22} /><h3>Specialist conversations</h3><p>Findings are designed to lead to focused conversations with qualified providers, not broad promises.</p></article><article><CheckCircle2 size={22} /><h3>Quick and actionable</h3><p>In around 15 minutes, move from broad business inputs to a clear list of areas worth reviewing.</p></article></div></div></section>
      <section className="faq-section section-space" id="faq"><div className="shell faq-layout"><div><span className="eyebrow">FAQ</span><h2>Questions, answered plainly.</h2><p>The DREAMS Score starts a business conversation with transparent limits and a practical outcome.</p></div><div className="faq-list">{faqItems.map(([question, answer], index) => <article className={index === openFaq ? "open" : ""} key={question}><button type="button" onClick={() => setOpenFaq(index === openFaq ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{index === openFaq && <p>{answer}</p>}</article>)}</div></div></section>
      <section className="closing-cta" id="book-a-review"><div className="shell"><span className="eyebrow">Ready when you are</span><h2>Discover the questions worth carrying into your next review.</h2><p>Take 15 minutes to build your estimate-based report. You decide what, if anything, is worth exploring next.</p><Link href="/assessment" className="button button-primary">Start my DREAMS Score <ArrowRight size={17} /></Link></div></section>
    </main><SectionNavigator items={landingSectionIndex} /><SiteFooter /><RobertGuide />
  </div>;
}
