import { Download, ExternalLink, History, RotateCcw } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { clearReportHistory, readReportHistory, type ReportHistoryEntry } from "@/lib/reportHistory";
import { formatEstimate } from "@shared/dreams";
import "@/components/ReportHistory.css";
function downloadPdf({ base64, filename, mimeType }: { base64: string; filename: string; mimeType: string }) { const bytes = Uint8Array.from(window.atob(base64), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: mimeType })); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); }
export function ReportHistoryPanel() { const [entries, setEntries] = useState<ReportHistoryEntry[]>(() => readReportHistory()); const [status, setStatus] = useState(""); const download = trpc.dreams.downloadBrandedPdfById.useMutation(); if (!entries.length) return null; const reDownload = (entry: ReportHistoryEntry) => { setStatus(`Preparing ${entry.companyName}'s color PDF…`); download.mutate({ id: entry.id }, { onSuccess: (file) => { downloadPdf(file); setStatus(`${entry.companyName}'s color PDF download has started.`); }, onError: () => setStatus("That report is no longer available. You can begin a new assessment at any time.") }); }; return <section className="report-history-panel paper-card" aria-labelledby="report-history-title"><div className="report-history-heading"><div><span className="eyebrow"><History size={14} /> Returning here?</span><h2 id="report-history-title">Your report history</h2><p>These links are saved only in this browser on this device.</p></div><button type="button" className="report-history-clear" onClick={() => { clearReportHistory(); setEntries([]); setStatus("Saved report history cleared from this browser."); }}><RotateCcw size={14} /> Clear history</button></div><div className="report-history-list">{entries.map((entry) => <article key={entry.id}><div><strong>{entry.companyName}</strong><span>Created {new Date(entry.generatedAt).toLocaleDateString()} · {formatEstimate(entry.totalPotentialValue)} potential value</span></div><div className="report-history-actions"><Link href={`/report/${entry.id}`}><ExternalLink size={14} /> View</Link><button type="button" disabled={download.isPending} onClick={() => reDownload(entry)}><Download size={14} /> PDF</button></div></article>)}</div><p className="report-history-status" role="status" aria-live="polite">{status}</p></section>; }
